// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKuTg8DdHM98K_94xYE1oONEVGcZ6tJOU',
    appId: '1:361698807507:web:c1d091455ed354c4f7ce26',
    messagingSenderId: '361698807507',
    projectId: 'd-for-doctors-app',
    authDomain: 'd-for-doctors-app.firebaseapp.com',
    storageBucket: 'd-for-doctors-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASJf1Nh0Fd754x0mAKqqte3dPeykly8EY',
    appId: '1:361698807507:android:abace61ca8580a24f7ce26',
    messagingSenderId: '361698807507',
    projectId: 'd-for-doctors-app',
    storageBucket: 'd-for-doctors-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXgElBOWMb__q33rPv3o9noofKfPhqah8',
    appId: '1:361698807507:ios:c01ed4803599e3f9f7ce26',
    messagingSenderId: '361698807507',
    projectId: 'd-for-doctors-app',
    storageBucket: 'd-for-doctors-app.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXgElBOWMb__q33rPv3o9noofKfPhqah8',
    appId: '1:361698807507:ios:c01ed4803599e3f9f7ce26',
    messagingSenderId: '361698807507',
    projectId: 'd-for-doctors-app',
    storageBucket: 'd-for-doctors-app.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKuTg8DdHM98K_94xYE1oONEVGcZ6tJOU',
    appId: '1:361698807507:web:45afe4048beca72bf7ce26',
    messagingSenderId: '361698807507',
    projectId: 'd-for-doctors-app',
    authDomain: 'd-for-doctors-app.firebaseapp.com',
    storageBucket: 'd-for-doctors-app.firebasestorage.app',
  );
}
