import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
// This import is for the Firebase configuration file you will generate in the next step.
import 'firebase_options.dart';
import 'package:mobile_app/widgets/user_role_wrapper.dart';

void main() async {
  // Ensure that the Flutter binding is initialized before calling Firebase.
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase. This needs to be done before the app runs.
  // The firebase_options.dart file will be generated by the FlutterFire CLI.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'D for Doctors',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const UserRoleWrapper(),
    );
  }
}


